ManageBookStore/Models/OrderDetail.cs
using System;
using System.Collections.Generic;

namespace ManageBookStore.Models;

public partial class OrderDetail
{
    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public int? Quantity { get; set; }

    public double? Price { get; set; }

    public virtual OrderCartImport Order { get; set; } = null!;

    public virtual Book Product { get; set; } = null!;
}

ManageBookStore/Pages/Cart.cshtml.cs
using ManageBookStore.Hubs;
using ManageBookStore.IRepositories;
using ManageBookStore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using System.Net.Http.Headers;
using System.Text.Json;

namespace ManageBookStore.Pages
{
    public class CartModel : PageModel
    {
        Prn221ManageStoreContext _context;
        IAccount _account;
        IOrderCartImport _orderCartImport;
        IBook _book;
        IOrderDetails _orderDetails;
        IHubContext<ProductHub> _productHub;

        public Account User { get; set; }   

        List<OrderDetail> ItemInCart { get; set; } = new List<OrderDetail>();

        public OrderCartImport Cart { get; set; } = new OrderCartImport();

        private readonly HttpClient client = null;

        private readonly string urlApi = "";

        public CartModel(
            Prn221ManageStoreContext context, 
            IAccount account,
            IOrderCartImport orderCartImport, 
            IBook book, 
            IOrderDetails orderDetails, 
            IHubContext<ProductHub> hubContext
            )
        {
            _context = context;
            _account = account;
            _orderCartImport = orderCartImport;
            _book = book;
            _orderDetails = orderDetails;
            _productHub = hubContext;
            client = new HttpClient();
            var contenType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contenType);
            urlApi = "http://localhost:5176/";
        }

        public async void GetAllBookInCart()
        {
            HttpResponseMessage httpResponseMessage = await client.GetAsync(urlApi + "getCart");
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string content = await httpResponseMessage.Content.ReadAsStringAsync();
                var option = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                //Array a = JsonSerializer.Deserialize<Array>(content, option);
                List<Book> books = JsonSerializer.Deserialize<List<Book>>(content, option);
                //return View(books);
            }
        }

        public void OnGet()
        {
            string accId = HttpContext.Session.GetString("account");
            if (!string.IsNullOrEmpty(accId))
            {
                User = _account.GetAccountById(int.Parse(accId));
                Cart = _orderCartImport.GetCart(User.Id);
            }
            else
            {
                string cartId = Request.Cookies["cart"];
                if (!string.IsNullOrEmpty(cartId))
                {
                    Cart = _orderCartImport.GetById(int.Parse(cartId));
                }
            }
            if (Cart!=null && Cart.OrderDetails.Count > 0)
            {
                CalQtyCart();
            }
        }

        public void CalQtyCart()
        {
            List<Book> listBook = _book.GetListById(Cart.OrderDetails.Select(o=>o.ProductId).ToList());
            foreach(Book book in listBook)
            {
                OrderDetail detail = Cart.OrderDetails.FirstOrDefault(o => o.ProductId == book.Id);
                if (book.Quantity == 0)
                {
                    Cart.OrderDetails.Remove(detail);
                    _orderCartImport.UpdateOrderCartImport(Cart);
                }else if(book.Quantity < detail.Quantity)
                {
                    detail.Quantity = book.Quantity;
                    _orderDetails.UpdateOrderDetails(detail);
                }

            }
        }

        public IActionResult OnPostRemove(int pid, int cartId)
        {
            _orderCartImport.RemoveItem(cartId, pid);
            return Redirect("cart");
        }

        public IActionResult OnPostCheckout(int cartId)
        {
            string accId = HttpContext.Session.GetString("account");
            if (!string.IsNullOrEmpty(accId))
            {
                _orderCartImport.Checkout(cartId);
                Checkout(cartId);
                _productHub.Clients.All.SendAsync("Reload");
            }
            else
            {
                return Redirect("login");
            }
            return Redirect("cart");
        }

        public void Checkout(int cartId)
        {
            Cart = _orderCartImport.GetById(cartId);
            foreach(OrderDetail od in Cart.OrderDetails)
            {
                Book b = _book.GetBookById(od.ProductId);
                b.Quantity -= od.Quantity;
                _book.UpdateBook(b);
            }
        }

        public IActionResult OnPostUpdate(int cartId)
        {
            Cart = _orderCartImport.GetById(cartId);
            List<OrderDetail> removeOrderDetail = new List<OrderDetail>();
            foreach(OrderDetail od in Cart.OrderDetails)
            {
                int qty = 0;
                try
                {
                    qty = int.Parse(Request.Form[od.ProductId.ToString()]);
                }catch(Exception)
                {
                    qty = 0;
                }
                int qtyInStock =(int) _book.GetBookById(od.ProductId).Quantity;
                if (qty>qtyInStock)
                {
                    qty=qtyInStock;
                }
                if (qty <= 0)
                {
                    removeOrderDetail.Add(od);
                }
                else
                {
                    Cart.OrderDetails.FirstOrDefault(o => o.ProductId == od.ProductId).Quantity = qty;
                }
            }
            if (removeOrderDetail.Count > 0)
            {
                foreach(OrderDetail od in removeOrderDetail)
                {
                    Cart.OrderDetails.Remove(od);
                }
            }
            _orderCartImport.UpdateOrderCartImport(Cart);
            return Redirect("cart");
        }
    }
}

ManageBookStore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ManageBookStore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ManageBookStore/Pages/Index.cshtml.cs
using ManageBookStore.IRepositories;
using ManageBookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Net.Http.Headers;
using System.Text.Json;

namespace ManageBookStore.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        Prn221ManageStoreContext _context;
        IBook _bookRepository;
        ICategories _categories;
        IOrderCartImport _orderCartImport;
        IOrderDetails _orderDetails;
        IAccount _account;

        public List<Category> Categories { get; set; } = new List<Category>();
        public List<Book> Books { get; set; } = new List<Book>();

        public string SearchQuery { get; set; }

        public Paging<Book> PagingPage { get; set; }=new Paging<Book>() ;

        public List<int> ListItemPerPage { get; set; } = new List<int> { 5, 10, 15, 20 };

        [BindProperty(Name ="item")]
        public int ItemPerPage { get; set; } = 5;

        public Account User { get;set; }

        private readonly HttpClient client = null;

        private readonly string urlApi = "";

        public IndexModel(ILogger<IndexModel> logger, IBook book, ICategories categories, IOrderCartImport orderCartImport, IOrderDetails orderDetails, IAccount account)
        {
            _logger = logger;
            _bookRepository = book;
            _categories = categories;
            _orderCartImport = orderCartImport;
            _orderDetails = orderDetails;   
            _account = account;
            client = new HttpClient();
            var contenType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contenType);
            urlApi = "http://localhost:5176/";
        }

        public async void GetAllBook()
        {
            HttpResponseMessage httpResponseMessage = await client.GetAsync(urlApi + "getBook");
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string content = await httpResponseMessage.Content.ReadAsStringAsync();
                var option = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                //Array a = JsonSerializer.Deserialize<Array>(content, option);
                List<Book> books = JsonSerializer.Deserialize<List<Book>>(content, option);
                //return View(books);
            }
        }

        public void OnGet(string? search, int? cat, int? page, int? item)
        {

            string accId = HttpContext.Session.GetString("account");
            if (!string.IsNullOrEmpty(accId))
            {
                User = _account.GetAccountById(int.Parse(accId));
            }
            Categories = _categories.GetAllCategories();
            Books = _bookRepository.GetAllInstockBook();
            if (cat != null && cat!= 0)
            {
                Books = _bookRepository.GetBookByCategory((int)cat);
            }
            if (!string.IsNullOrEmpty(search))
            {
                SearchQuery = search.ToLower();
                if (Books != null)
                {
                    Books = Books.Where(b => b.Name.ToLower().Contains(SearchQuery) || (b.Description!= null && b.Description.Contains(SearchQuery))).ToList();
                }
            }
            if (page == null)
            {
                try
                {
                    page = int.Parse(Request.Query["page"]);
                }catch(Exception) 
                {
                    page = 1;
                }
            }
            if (item ==null || item  <= 0)
            {
                item = 5;
            }
            ItemPerPage = (int)item;
            PagingPage.ListItem = Books;
            PagingPage.ItemPerPage = ItemPerPage;
            PagingPage.CalTotalPage();
            if (page<1 || page > PagingPage.TotalPage)
            {
                page = 1;
            }
            Books = PagingPage.GetListPageIndex((int)page);
        }

        public IActionResult OnPost(int pid)
        {
            string accId = HttpContext.Session.GetString("account");
            OrderDetail cartItem = new OrderDetail();
            cartItem.ProductId = pid;
            cartItem.Quantity = 1;
            cartItem.Price = _bookRepository.GetBookById(pid).Price;
            if (accId == null)
            {
                CookieOptions cookieOptions = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(3)
                };

                string cartId = Request.Cookies["cart"];
                if (string.IsNullOrEmpty(cartId) == true || cartId == "[]")
                {
                    OrderCartImport cart = new OrderCartImport();
                    cart.TotalPrice = 0;
                    cart.FinalPrice = 0;
                    cart.Type = "cart";
                    cart.RemoteIp = HttpContext.Connection.RemoteIpAddress?.ToString();
                    _orderCartImport.AddOrderCartImport(cart);
                    _orderCartImport.AddItemToCart(cart.Id, cartItem);
                    Response.Cookies.Append(
                    "cart",
                    cart.Id.ToString(),
                    cookieOptions
                    );
                }
                else
                {
                    _orderCartImport.AddItemToCart(int.Parse(cartId), cartItem);
                }
            }
            else
            {
                OrderCartImport cartAcc = _orderCartImport.GetCart(int.Parse(accId));
                if (cartAcc != null)
                {
                    _orderCartImport.AddItemToCart(cartAcc.Id, cartItem);
                }
                else
                {
                    OrderCartImport cart = new OrderCartImport();
                    cart.TotalPrice = 0;
                    cart.FinalPrice = 0;
                    cart.Type = "cart";
                    cart.AccId = int.Parse(accId);
                    cart.RemoteIp = HttpContext.Connection.RemoteIpAddress?.ToString();
                    _orderCartImport.AddOrderCartImport(cart);
                    _orderCartImport.AddItemToCart(cart.Id, cartItem);
                }
            }
            return Redirect("index");
        }
    }
}

ManageBookStore/Pages/Login.cshtml.cs
using ManageBookStore.IRepositories;
using ManageBookStore.Models;
using ManageBookStore.Repositories;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ManageBookStore.Pages
{
    public class LoginModel : PageModel
    {
        Prn221ManageStoreContext _context;
        IAccount _account;
        IOrderCartImport _orderCartImport;


        public LoginModel(Prn221ManageStoreContext context, IAccount account, IOrderCartImport orderCartImport)
        {
            _context = context;
            _account = account;
            _orderCartImport = orderCartImport;
        }

        [BindProperty]
        public string UserName { get; set; }

        [BindProperty]
        public string Password { get; set; }
        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            Account a = _account.GetAccountByLogin(UserName, Password);
            if (a == null)
            {
                ViewData["error"] = "Username (or email) and password is not match any account!";
                return Page();
            }
            HttpContext.Session.SetString("account", a.Id.ToString());

            string cartId = Request.Cookies["cart"];
            if (!string.IsNullOrEmpty(cartId))
            {
                OrderCartImport cartAcc = _orderCartImport.GetCart(a.Id);
                if (cartAcc == null)
                {
                    _orderCartImport.AddAccToCart(int.Parse(cartId), a.Id);
                }
                else
                {
                    _orderCartImport.MergeCartLogin(int.Parse(cartId), cartAcc.Id);
                }
                Response.Cookies.Delete("cart");
            }

            if (_account.CheckRole(a.Id, "admin"))
            {
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Role, "Admin"),
                    };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return Redirect("/admin/books");
            }

            return Redirect("index");
        }
    }
}

ManageBookStore/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManageBookStore.Pages
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.Remove("account");
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("index");
        }
    }
}

ManageBookStore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManageBookStore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ManageBookStore/Pages/Cart.cshtml
@page
@model ManageBookStore.Pages.CartModel
@{
}
<style>
    .bordered-table {
        border-collapse: collapse;
    }

        .bordered-table th,
        .bordered-table td {
            border: 1px solid black;
            padding: 8px;
        }
</style>
<div>
    <div style="float:left; width:20%; border-right:1px solid;">
        @if (Model.User != null && Model.User.UserName != null)
        {
            <h3>@Model.User.UserName</h3>
            <a href="logout">Logout</a><br />
            <a href="../">Homepage</a><br />
        }
        else
        {
            <a href="login">Login</a><br />
            <a href="register">Register</a>
        }
    </div>
    <div>
        @if(Model.Cart==null || Model.Cart.OrderDetails.Count <= 0)
        {
            <h2 style="color:red">Cart empty</h2>
        }
        else
        {
            <table class="bordered-table">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <form asp-page-handler="Update" method="post">
                        @foreach (var item in Model.Cart.OrderDetails)
                        {
                        <tr>
                            <td><img src="@item.Product.Image" style="max-width: 100px;" /></td>
                            <td>@item.Product.Name</td>
                            <td>@item.Product.Price</td>
                            <td><input type="number" name="@item.ProductId" value="@item.Quantity" /></td>
                            <td>@(item.Product.Price * item.Quantity)</td>
                            <td>
                                @*<form asp-page-handler="Remove" method="post">*@
                                    @*<input type="hidden" name="cartId" value="@Model.Cart.Id">*@
                                    <input type="hidden" name="pid" value="@item.ProductId">
                                    <button type="submit">Remove</button>
                                @*</form>*@
                            </td>
                        </tr>
                        }
                        <br>
                        <tr>
                            <td><input type="hidden" name="cartId" value="@Model.Cart.Id"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><button type="submit">Update cart</button></td>
                        </tr>
                    </form>
                </tbody>
            </table>
            <br />
            <br />
            <table>
                <tr>
                    <td>Total Price</td>
                    <td>@Model.Cart.TotalPrice</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <form asp-page-handler="Checkout" method="post">
                            <input type="hidden" name="cartId" value="@Model.Cart.Id">
                            <button type="submit">Checkout</button>
                        </form>
                    </td>
                </tr>
            </table>
        }
    </div>
</div>

ManageBookStore/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<style>
    .bordered-table {
        border-collapse: collapse;
    }

        .bordered-table th,
        .bordered-table td {
            border: 1px solid black;
            padding: 8px;
        }
</style>
<div class="text-center">
    <div style="width:20%; float:left; border-right: 1px solid black;">
        <div>
            @if(Model.User!=null && Model.User.UserName != null)
            {
                <h2>@Model.User.UserName</h2>
                <a href="logout">Logout</a>
                <br />
                <a href="order">Orders</a>
            }
            else
            {
                <a href="login">Login</a>
                <br />
                <a href="register">Register</a>
            }
            <br />
            <a href="cart">My Cart</a>
            <br />
        </div>
        <div>
            <h3>Thể loại</h3>
            <div>
                <table>
                    @foreach (var c in Model.Categories)
                    {
                        <tr>
                            <td><a href="index?cat=@c.Id">@c.Name</a></td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
    <div style="width:60%; float:left;">
        <div>
            <form id="paging">
                <input name="search" value="@Model.SearchQuery" />
                <button type="submit">Search</button>  
                <div style="float:right;">
                        <label>Item per page</label>
                        <select name="item" onchange="submitForm()">
                            @foreach (int i in Model.ListItemPerPage)
                            {
                                if (Model.ItemPerPage == i)
                                {
                                    <option value="@i" selected>@i</option>
                                }
                                else
                                {
                                    <option value="@i">@i</option>
                                }

                            }
                        </select>
                </div>
            </form>
            
        </div>
        <h2>            </h2>
        <div>
            @if (Model.Books.Count() < 1)
            {
                <h1>There isn't any book here!</h1>
            }
            else
            {
                <table class="bordered-table">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Book Title</th>
                            <th>Book Description</th>
                            <th>Price</th>
                            <th>Book detail</th>
                            <th>Add to cart</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var b in Model.Books)
                        {
                            <tr>
                                <td><img src="@b.Image" style="max-width: 100px;"></td>
                                <td>@b.Name</td>
                                <td>@b.Description</td>
                                <td>@b.Price</td>
                                <td><a href="addBook?id=@b.Id">View details</a></td>
                                <td>
                                    <form method="post">
                                        <input type="hidden" name="pid" value="@b.Id">
                                        <button type="submit">Add to cart</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div>
                    @for (int i = 1; i <= Model.PagingPage.TotalPage; i++)
                    {
                        <a href="index?page=@i">@i</a>
                    }
                </div>
            }
        </div>
    </div>
</div>
<script>
    function submitForm() {
        document.getElementById('paging').submit();
    }
</script>

ManageBookStore/Pages/Login.cshtml
@page
@model ManageBookStore.Pages.LoginModel
@{
}
<div>
    @if (ViewData["error"] != "")
    {
        <h3 style="color:red">@ViewData["error"]</h3>
    }
    <form method="post">
        <table>
            <tr>
                <td>UserName or Email: </td>
                <td><input type="text" name="UserName" value="@Model.UserName" /></td>
            </tr>
            <tr>
                <td>Password: </td>
                <td><input type="password" name="Password" value="@Model.Password" /></td>
            </tr>
            <tr>
                <td></td>
                <td><button type="submit">Login</button></td>
            </tr>
        </table>
    </form>
</div>

ManageBookStore/Pages/Logout.cshtml
@page
@model ManageBookStore.Pages.LogoutModel
@{
}

ManageBookStore/Pages/Order.cshtml
@page
@model ManageBookStore.Pages.OrderModel
@{
}
<style>
    .bordered-table {
        border-collapse: collapse;
    }

        .bordered-table th,
        .bordered-table td {
            border: 1px solid black;
            padding: 8px;
        }
</style>
<div>
    <div style="width:20%; float:left; border-right: 1px solid black;">
        <div>
            @if (Model.User != null && Model.User.UserName != null)
            {
                <h2>@Model.User.UserName</h2>
                <a href="logout">Logout</a>
            }
            else
            {
                <a href="login">Login</a>
                <br />
                <a href="register">Register</a>
            }
            <br />
            <a href="cart">My Cart</a>
            <br />
        </div>
    </div>
    <div style="width:60%; float:left;">
        <div>
            @if (Model.ListOrder.Count() < 1)
            {
                <h1>There isn't any order!</h1>
            }
            else
            {
                <table class="bordered-table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Created time</th>
                            <th>Total Price</th>
                            <th>View detail</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var b in Model.ListOrder)
                        {
                            <tr>
                                <td>@b.Id</td>
                                <td>@b.CreatedTime</td>
                                <td>@b.TotalPrice</td>
                                <td><a href="orderDetail?id=@b.Id">View details</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>
<script>

</script>

ManageBookStore/Pages/OrderDetail.cshtml
@page
@model ManageBookStore.Pages.OrderDetailModel
@{
}

<style>
    .bordered-table {
        border-collapse: collapse;
    }

        .bordered-table th,
        .bordered-table td {
            border: 1px solid black;
            padding: 8px;
        }
</style>
<div>
    <div style="width:20%; float:left; border-right: 1px solid black;">
        <div>
            @if (Model.User != null && Model.User.UserName != null)
            {
                <h2>@Model.User.UserName</h2>
                <a href="logout">Logout</a>
            }
            else
            {
                <a href="login">Login</a>
                <br />
                <a href="register">Register</a>
            }
            <br />
            <a href="cart">My Cart</a>
            <br />
        </div>
    </div>
    <div style="width:60%; float:left;">
        <div>
            @if (Model.ListOrderDetails.Count() < 1)
            {
                <h1>There isn't any order!</h1>
            }
            else
            {
                <table class="bordered-table">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total Price</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model.ListOrderDetails)
                        {
                            <tr>
                                <td><img src="@item.Product.Image" style="max-width: 100px;" /></td>
                                <td>@item.Product.Name</td>
                                <td>@item.Product.Price</td>
                                <td>@item.Quantity</td>
                                <td>@(item.Product.Price * item.Quantity)</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <br />
                <h5>Total price: <b>@Model.Order.Id</b></h5>
            }
        </div>
    </div>
</div>

ManageBookStore/Pages/Register.cshtml
@page
@model ManageBookStore.Pages.RegisterModel
@{
}
<div>
    @if (ViewData["error"] != "")
    {
        <h3 style="color:red">@ViewData["error"]</h3>
    }
    <form method="post">
        <table>
            <tr>
                <td>UserName: </td>
                <td><input type="text" name="UserName" value="@Model.UserName" /></td>
            </tr>
            <tr>
                <td>FullName: </td>
                <td><input type="text" name="FullName" value="@Model.FullName" /></td>
            </tr>
            <tr>
                <td>Password: </td>
                <td><input type="password" name="Password" value="@Model.Password" /></td>
            </tr>
            <tr>
                <td>Repeat password: </td>
                <td><input type="password" name="RePass" value="@Model.RePass" /></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><input type="text" name="Email" value="@Model.Email" /></td>
            </tr>
            <tr>
                <td>Phone</td>
                <td><input type="number" name="Phone" value="@Model.Phone" /></td>
            </tr>
            <tr>
                <td>Address</td>
                <td><input type="text" name="Addresses" value="@Model.Addresses" /></td>
            </tr>
            <tr>
                <td></td>
                <td><button type="submit">Register</button></td>
            </tr>
        </table>
    </form>
</div>